# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: actions.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ractions.proto\"\'\n\x12\x44oSomethingRequest\x12\x11\n\tsomething\x18\x01 \x01(\x08\"0\n\x13\x44oSomethingResponse\x12\x19\n\x11somethingResponse\x18\x01 \x01(\t\"i\n\x16RemoteExecutionRequest\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x05 \x01(\t\"9\n\x17RemoteExecutionResponse\x12\x0e\n\x06stdout\x18\x01 \x01(\t\x12\x0e\n\x06stderr\x18\x02 \x01(\t2\x8b\x01\n\x07\x41\x63tions\x12:\n\rDoSomthingNew\x12\x13.DoSomethingRequest\x1a\x14.DoSomethingResponse\x12\x44\n\x0fRemoteExecution\x12\x17.RemoteExecutionRequest\x1a\x18.RemoteExecutionResponseb\x06proto3')



_DOSOMETHINGREQUEST = DESCRIPTOR.message_types_by_name['DoSomethingRequest']
_DOSOMETHINGRESPONSE = DESCRIPTOR.message_types_by_name['DoSomethingResponse']
_REMOTEEXECUTIONREQUEST = DESCRIPTOR.message_types_by_name['RemoteExecutionRequest']
_REMOTEEXECUTIONRESPONSE = DESCRIPTOR.message_types_by_name['RemoteExecutionResponse']
DoSomethingRequest = _reflection.GeneratedProtocolMessageType('DoSomethingRequest', (_message.Message,), {
  'DESCRIPTOR' : _DOSOMETHINGREQUEST,
  '__module__' : 'actions_pb2'
  # @@protoc_insertion_point(class_scope:DoSomethingRequest)
  })
_sym_db.RegisterMessage(DoSomethingRequest)

DoSomethingResponse = _reflection.GeneratedProtocolMessageType('DoSomethingResponse', (_message.Message,), {
  'DESCRIPTOR' : _DOSOMETHINGRESPONSE,
  '__module__' : 'actions_pb2'
  # @@protoc_insertion_point(class_scope:DoSomethingResponse)
  })
_sym_db.RegisterMessage(DoSomethingResponse)

RemoteExecutionRequest = _reflection.GeneratedProtocolMessageType('RemoteExecutionRequest', (_message.Message,), {
  'DESCRIPTOR' : _REMOTEEXECUTIONREQUEST,
  '__module__' : 'actions_pb2'
  # @@protoc_insertion_point(class_scope:RemoteExecutionRequest)
  })
_sym_db.RegisterMessage(RemoteExecutionRequest)

RemoteExecutionResponse = _reflection.GeneratedProtocolMessageType('RemoteExecutionResponse', (_message.Message,), {
  'DESCRIPTOR' : _REMOTEEXECUTIONRESPONSE,
  '__module__' : 'actions_pb2'
  # @@protoc_insertion_point(class_scope:RemoteExecutionResponse)
  })
_sym_db.RegisterMessage(RemoteExecutionResponse)

_ACTIONS = DESCRIPTOR.services_by_name['Actions']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DOSOMETHINGREQUEST._serialized_start=17
  _DOSOMETHINGREQUEST._serialized_end=56
  _DOSOMETHINGRESPONSE._serialized_start=58
  _DOSOMETHINGRESPONSE._serialized_end=106
  _REMOTEEXECUTIONREQUEST._serialized_start=108
  _REMOTEEXECUTIONREQUEST._serialized_end=213
  _REMOTEEXECUTIONRESPONSE._serialized_start=215
  _REMOTEEXECUTIONRESPONSE._serialized_end=272
  _ACTIONS._serialized_start=275
  _ACTIONS._serialized_end=414
# @@protoc_insertion_point(module_scope)
